# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#--------------------------------------------------------------------------------------------------
 config.vm.define "web", primary: true do |web|
  	
 	web.vm.box = "/home/Student/Desktop/vagrant/mntlab/sbeliakou-vagrant-centos-6.7-x86_64.box"
  	web.vm.hostname = "web"
  	
	web.vm.network "private_network", ip: "192.168.25.10"
  	web.vm.provider "virtualbox" do |machine|
		machine.name = "web-frontend"
		machine.cpus = 1
		machine.memory = 512
	end
	web.vm.provision "shell", path: "sources/web.sh"
	web.vm.provision "shell", inline: "echo The WEB-server is DONE!"
  end
#---------------------------------------------------------------------------------------------------
 config.vm.define "app" do |app|
	app.vm.box = "/home/Student/Desktop/vagrant/mntlab/sbeliakou-vagrant-centos-6.7-x86_64.box"
	app.vm.hostname = "db"
	app.vm.network "private_network", ip: "192.168.25.11"
  	app.vm.provider "virtualbox" do |machine|
        	machine.name = "db-backend"
		machine.customize ["modifyvm", :id, "--cpuexecutioncap", "35"]
		machine.memory = 1024
	end
	app.vm.provision "shell", path: "sources/app.sh"
        app.vm.provision "shell", inline: "echo The APP-server is DONE!"
 end 
#----------------------------------------------------------------------------------------------------
 config.vm.synced_folder "sources/", "/home/sources",
 owner:"vagrant", group:"vagrant",
 create:true
	
end  

